### PR TITLE
Class diagram and tests

### PR DESCRIPTION
**Pull request by glaand**
@cybrox Two things.
1. Could you please peer review the class diagram?
2. I could not manage to have it properly formatted at Latex. After the intro text, there is now a big space between text and the diagram, since the diagram is saved as a pdf. Maybe you know how to handle this?

### CODE REVIEW

**Comment by glaand** [comment]
@cybrox i accidentally have pushed the test cases for the documentation into this branch. Could you please review this aswell?
https://github.com/IBZTI2018/TI3-WT-SA/issues/44

**Comment by cybrox** [comment]
Test list looks :+1: 

For the diagram, it looks really good. I think the easiest way would be to split it into 3 diagrams (engines, pages and models) with separate draw.io files and export each of them as separate PNG. That should also solve the layout issues, since PNGs are very nice to embed.

**Comment by glaand** [comment]
Need to write test cases for story-41 (Open image in a new tab). Wait until story-41 is released

**Comment by glaand** [comment]
@cybrox I've done the changes. What you think?

**Comment by cybrox** [comment]
Looks :+1: but the Image and Home changes are still in this branch as well, those would need to be removed.

Does image embedding in the docs work for you? For me, it only works when I rename the files to `-classes.png` instead of `.classes.png`, because LaTeX does not recognize the file types.

**Pull request closed without merging**
