### PR TITLE
Open image with link+

### PR DESCRIPTION
**Pull request by glaand**

### CODE REVIEW

**Comment by cybrox** [comment]
Merge target branch should be changed to master.

From testing, it's a bit weird. Opening the data URI in a new tab if it's a PNG works in Chrome but does not work when it's a JPEG. However, if I open the development console and open the link from there, it also works.

Maybe we need to add an `/image` page after all :(

**Comment by glaand** [comment]
> 
> 
> Merge target branch should be changed to master.
> 
> From testing, it's a bit weird. Opening the data URI in a new tab if it's a PNG works in Chrome but does not work when it's a JPEG. However, if I open the development console and open the link from there, it also works.
> 
> Maybe we need to add an `/image` page after all :(

@cybrox Alright, i will create a page for that 👍

**Review by cybrox — APPROVED** [review]
Looks good. :100: :+1: 

I think we can remove the `target=_blank` from the link since the page has a back button and you end up with 2 tabs when clicking back but that's the only minor improvement idea. :)

**Comment by glaand** [comment]
> Looks good. 💯 👍
> 
> I think we can remove the `target=_blank` from the link since the page has a back button and you end up with 2 tabs when clicking back but that's the only minor improvement idea. :)

True, didn't thought about that 👍  gonna change it

**Pull request merged**
